main:
  url: https://api.github.com/graphql
  graphQLQuery: query {viewer{contributionsCollection {contributionCalendar {isHalloween totalContributions weeks { contributionDays { contributionCount date color}}}}}}
